# Generated by Django 6.0.3 on 2026-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_style',
            field=models.CharField(choices=[('btn-primary', 'Primary — solid blue'), ('btn-secondary', 'Secondary — solid dark'), ('btn-outline', 'Outline — bordered'), ('btn-ghost', 'Ghost — text only')], default='btn-primary', help_text='Visual style of the Call to Action button', max_length=20, verbose_name='Hero CTA style'),
        ),
    ]
