# Generated by Django 6.0.3 on 2026-03-03 18:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_hero_cta_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich text'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'template': 'home/blocks/image_block.html'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Button text'}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Link to page'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('btn-primary', 'Primary — solid blue'), ('btn-secondary', 'Secondary — solid dark'), ('btn-outline', 'Outline — bordered'), ('btn-ghost', 'Ghost — text only')], 'label': 'Style'}), 5: ('wagtail.blocks.StructBlock', [[('text', 2), ('link', 3), ('style', 4)]], {})}, verbose_name='Content blocks'),
        ),
    ]
