# Generated by Django 6.0.3 on 2026-03-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hydrogenregistrationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Main heading in the hero section', max_length=255),
        ),
    ]
