# Generated by Django 6.0.3 on 2026-03-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_hero_cta_link_homepage_hero_cta_subtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_style',
            field=models.CharField(choices=[('btn-secondary', 'Secondary — pink/red'), ('btn-primary', 'Primary — blue'), ('btn-white', 'White — white bg, blue text'), ('btn-outline', 'Outline — blue border and text')], default='btn-secondary', max_length=20, verbose_name='CTA button style'),
        ),
    ]
