# Generated by Django 6.0.3 on 2026-03-10 19:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cards',
            field=wagtail.fields.StreamField([('horizontal_card', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Text above title (optional)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ul', 'ol', 'link'], 'label': 'Body text'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image — shown on the left (optional)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('supertitle', 0), ('title', 1), ('text', 2), ('image', 3)]], {})}, verbose_name='Cards'),
        ),
    ]
