# Generated by Django 6.0.3 on 2026-03-11 11:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_homepage_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('horizontal_card', 4), ('rich_text', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Text above title (optional)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ul', 'ol', 'link'], 'label': 'Body text'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image — shown on the left (optional)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('supertitle', 0), ('title', 1), ('text', 2), ('image', 3)]], {}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ul', 'ol', 'link', 'h2', 'h3'], 'label': 'Rich text'})}, verbose_name='Body (free-form content)'),
        ),
    ]
