# Generated by Django 6.0.3 on 2026-03-11 12:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_body'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField()),
                ('intro', models.CharField(blank=True, help_text='Short summary shown on the listing page', max_length=300)),
                ('body', wagtail.fields.StreamField([('horizontal_card', 4), ('rich_text', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Text above title (optional)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ul', 'ol', 'link'], 'label': 'Body text'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image — shown on the left (optional)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('supertitle', 0), ('title', 1), ('text', 2), ('image', 3)]], {}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ul', 'ol', 'link', 'h2', 'h3'], 'label': 'Rich text'})})),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
